version: "2"
services:
  zookeeper:
    image: solsson/zookeeper
  kafka:
    image: solsson/kafka
    links:
      - zookeeper
  client:
    build: ../
    image: localhost:5000/yolean/kafka-topic-client:$PUSH_TAG
    labels:
      com.yolean.build-contract: ""
      com.yolean.build-target: ""
    links:
      - zookeeper
  test:
    build: ./node-client
    labels:
      com.yolean.build-contract: ""
    links:
      - kafka
